name: ebs
channels:
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - matplotlib
  - pip
  - pandas
  - pytest
  - jupyter
  - pip:
      - emcee
      - exosims
      - corner
      - dynesty
